### ISSUE TITLE
Dockerisation runs as `su`

### ISSUE THREAD

**Issue by owenblacker** [alphagov/re-request-an-aws-account#279]
At the moment, the dockerfile runs everything as `su`. We should change it to uncomment line 11's

```dockerfile
RUN chown -R user:user /opt/app
```

so that the subsequent code can run as `USER user` instead.

This is better security practice.

**Comment by tabroughton** [comment]
Would you like to do this is the current branch in the PR? seems like a quick add and agree with you that we should run as `user:user`

**Comment by owenblacker** [comment]
Didn't spot your reply until now @tabroughton ; would you like to add this to the backlog when you get a chance?

**Comment by tabroughton** [comment]
this is part of docker file
